**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!turbo.json
!tsconfig.json

!apps/landing
!apps/landing/**

!packages/types
!packages/types/**
!packages/ui
!packages/ui/**
!packages/utils
!packages/utils/**
